### PR TITLE
fix: Support additional chords and tuning notes

### LINKED ISSUE #18: Some chord names not highlighted
Certain common chord names aren't recognised:
Example: 

- Bm7b5
- Cmaj9#11
- Adim

etc...

### PR DESCRIPTION
**Pull request by c-d**
Fixes #18 

Credit to @Rbekking for regex changes.

### CODE REVIEW

**Comment by gusper** [comment]
Will get it merged in and published later today. Thanks!

**Comment by gusper** [comment]
Thanks @c-d and @RBekking! I'll get the extension updated on the marketplace soon as well.

**Comment by contributor** [comment]
@gusper is the extension updated? VS code shows it with "Last updated 10/10/2022, 03:55:00", but Bm7b5 chord is still no yet highlighted...

**Comment by gusper** [comment]
@contributor I just checked, and it does highlight for me. However, it's possible I messed something up in the update. I'll take a look. Truth is I had to make several updates to the extension to get it to publish as it had been 4 years since I'd updated it and that time 4 years ago was my only other experience building VS Code extensions.

**Comment by gusper** [comment]
@contributor - I checked on separate Windows PC and a Mac. Both worked fine. However, the Mac is one I hadn't used VS Code on in ages. It did _not_ highlight Bm7b5 at first until after I updated VS Code itself to the latest version. After the update, I got a notification that the SongTxt extension needed to be reloaded. Once reloaded, it was also highlighting it correctly. 

Still possible I messed something up, but it does seem to work fine for me on three different machines. Can you make sure your VS Code is up to date and maybe uninstall and reinstall SongTxt?

**Comment by contributor** [comment]
@gusper thanks. Restarted vscode and it highlights the chord now. So I confirm the extension works ok, and it was my environment/cache issue. Thank you for the great extension!

**Comment by contributor** [comment]
Chords like (C) or Am* are still not highlighted. Not sure how common is this, and worth creating another issue. Song example: https://tabs.ultimate-guitar.com/tab/scorpions/wind-of-change-chords-102896

**Comment by gusper** [comment]
@contributor Happy to hear a restart did the trick! 

I'm not sure (C) and Am* are all that standard to be honest, but if you see it enough, please feel free to log an issue and I'll try to get to it.

**Comment by contributor** [comment]
These are not standard in music in general. But it is part of ultimate-guitar guidelines:
image

Star character supposes to be explained in legend. I've seen chords like Am*, Am**. Not sure about three or more stars.
Parenthesis - not sure what are they for.

Though both are recognized as valid by ultimate-guitar (and highlighted in bold). 

What about efforts? Would it be easy and won't break other things?

**Pull request merged**
